#' Long Format Date
#'
#' @param date Currently a Date format, as provided by Sys.Date()
#' @param ... Date.
#'
#' @return character date
#' @export
# @importFrom scales label_ordinal
#'
#' @examples
#' format_date()
#' format_date(as.Date("2023-01-01"))
format_date <- function(date = Sys.Date(), ...) {
  d <- as.integer(format(date, "%d"))
  if(requireNamespace("scales", quietly = TRUE)) {
    d <- scales::label_ordinal()(d)
  } else {
    d <- label_ordinal(d)
  }
  my <- format(date, "%B, %Y")
  paste(d, my)
}
# code generated by claude based on scales::label_ordinal
# label ordinal
label_ordinal <- function(prefix = "", suffix = "", big.mark = ",",
                          rules = ordinal()) {
  function(x) {
    # Format the base numbers
    x_formatted <- format(x, big.mark = big.mark, trim = TRUE)
    # Apply ordinal rules
    ordinals <- rules(x)
    # Combine with prefix and suffix
    paste0(prefix, x_formatted, ordinals, suffix)
  }
}

ordinal <- function() {
  function(x) {
    # Convert to integer to handle the logic
    x <- as.integer(x)
    # Handle special cases for 11th, 12th, 13th
    if_teen <- (x %% 100) %in% 11:13
    # Get the last digit for regular rules
    last_digit <- x %% 10
    # Apply ordinal rules
    suffix <- ifelse(if_teen, "th",
                     ifelse(last_digit == 1, "st",
                            ifelse(last_digit == 2, "nd",
                                   ifelse(last_digit == 3, "rd", "th"))))
    suffix
  }
}
